import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import React from "react";

export default function TermsAndConditions() {
  return (
    <>
      <Navbar />
      <div className="bg-blue-50 flex flex-col justify-start items-start px-4 sm:px-8 md:px-20 lg:px-40 py-10 sm:py-16 md:py-20">
        <h1 className="mt-10 sm:mt-16 md:mt-20 text-4xl sm:text-5xl md:text-7xl font-semibold leading-tight">
          TERMS AND
        </h1>
        <h1 className="text-4xl sm:text-5xl md:text-7xl font-semibold">
          CONDITIONS
        </h1>
      </div>
      <div className="flex flex-col justify-start items-start px-4 sm:px-8 md:px-20 lg:px-40 py-10 sm:py-16 md:py-20 w-full max-w-6xl mx-auto">
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">1. Introduction</h2>
          <p>This document serves as an electronic record under the Information Technology Act, 2000 and applicable rules, and is generated by a computer system without requiring any physical or digital signatures. This document outlines the terms and conditions (“Terms of Use”) governing your access to and use of the platform Stoxii (“Platform”) and the services offered through it.</p>
          <p className="mt-2">By using our Platform, you confirm that you have read, understood, and agreed to abide by these Terms of Use. These terms govern your use of the Platform, its associated website, mobile site, and mobile applications, owned by Stoxii (known as Stoxii Consultancy Services), hereinafter referred to as “we”, “our”, “us” (“Platform Owner”).</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">2. Acceptance of Terms</h2>
          <p>By accessing or using the Platform, you agree to comply with the Terms of Use and any applicable policies. If you do not agree to these Terms, please refrain from using the Platform.</p>
          <p className="mt-2">These Terms of Use are subject to modification at any time. We recommend that you review these Terms periodically to stay updated with any changes.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">3. Account Registration</h2>
          <p>To access and use the services, you agree to provide accurate, current, and complete information during registration. You are responsible for any actions performed through your registered account.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">4. Use of Services</h2>
          <p>You agree to use the Platform and services in a lawful manner and solely for the purposes intended by the Platform. Unauthorized use of the Platform may result in termination of your access and potential legal action.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">5. Intellectual Property</h2>
          <p>The content on the Platform, including but not limited to designs, layouts, graphics, and software, is owned by the Platform Owner or licensed to it. You do not have any intellectual property rights over the content and shall not use it without permission.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">6. Accuracy and Availability</h2>
          <p>While we strive to provide accurate and up-to-date information, we do not guarantee the accuracy, completeness, or suitability of the materials and services provided. Your use of the Platform and services is at your own risk.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">7. Payment and Charges</h2>
          <p>By availing of any services, you agree to pay the applicable charges, including any taxes or fees, as specified during the transaction. Payments are processed securely through authorized payment gateways.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">8. Third-Party Links</h2>
          <p>Our Platform may contain links to third-party websites. We are not responsible for the content, policies, or practices of these websites. You acknowledge that accessing these links is done at your own risk.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">9. Indemnification</h2>
          <p>You agree to indemnify and hold harmless the Platform Owner, its affiliates, employees, officers, and agents from any third-party claims arising from your violation of these Terms of Use or any applicable laws.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">10. Limitation of Liability</h2>
          <p>Under no circumstances shall the Platform Owner be liable for any indirect, incidental, or consequential damages, including but not limited to loss of profits, data, or use, arising from your use or inability to use the Platform.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">11. Force Majeure</h2>
          <p>We shall not be held liable for any delay or failure in performance due to events beyond our reasonable control, including but not limited to natural disasters, war, labor disputes, or system failures.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">12. Governing Law</h2>
          <p>These Terms of Use shall be governed by and construed in accordance with the laws of India. Any disputes arising in connection with these Terms shall be resolved in the exclusive jurisdiction of the courts in Bangalore, Karnataka.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">13. Termination</h2>
          <p>We reserve the right to suspend or terminate your access to the Platform if we determine that you have violated any of these Terms.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">14. Privacy Policy</h2>
          <p>For information on how we collect and use your data, please refer to our Privacy Policy, which forms an integral part of these Terms of Use.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">15. Dispute Resolution</h2>
          <p>In case of any disputes, concerns, or communications, you are encouraged to contact us through the provided contact details. We aim to resolve any issues in a fair and timely manner.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4 mt-10">Important Trading Disclaimers</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li><strong>No Guarantees:</strong> Stoxii and its research analyst do not guarantee the accuracy or success of any trading call for equity trading. Clients should use their own discretion and judgment when executing trades based on the provided calls.</li>
            <li><strong>No Liability for Losses:</strong> Stoxii and its research analyst are not liable for any losses incurred by clients while executing trades based on the provided calls equity trading. Clients acknowledge and accept the inherent risks associated with trading in financial markets.</li>
            <li><strong>Client Responsibility:</strong> Clients are solely responsible for their trading decisions and outcomes in both option and equity trading. They should conduct their own research, assess their risk tolerance, and make informed decisions based on their individual circumstances.</li>
            <li>By engaging with Stoxii’s trading calls for equity trading, clients agree to indemnify and hold harmless Stoxii and its research analyst from any losses, damages, or liabilities incurred as a result of their trading activities.</li>
            <li><strong>Stoxii’s Commitment:</strong> Stoxii is committed to providing transparent and responsible trading guidance in equity markets. Clients are encouraged to approach trading with caution and diligence to minimize risks and maximize opportunities.</li>
          </ul>
        </section>
        <section>
          <p className="font-medium mt-10 sm:mt-16 md:mt-20">
            By using our Platform, you acknowledge and agree to the Terms and Conditions outlined above.
          </p>
        </section>
      </div>
      <Footer />
    </>
  );
}
